spring:
  profiles:
    #active: @spring.profiles.active@
   active: development
  config:
    # Для считывания всех общих конфигураций
    # Для запуска теста и приложения локально,
    # почему-то путь меняется, поэтому включим оба и чтобы не ругался если файла нет
    import: optional:file:./gpb-config/*/ , optional:file:../gpb-config/*/