spring:
 profiles:
  active: production
---
spring:
  profiles: development
  #kafka:
   #bootstrap-servers: localhost:9092
    # consumer:
     #  group-id: LOCAL
refresh:
 rate: 2
---
spring:
 profiles: production
refresh:
 rate: 211